In [2]:
import numpy as np

In [3]:
a, b, c, d, e = 0.8, 1, 1.2, 1.4, 1.6

a1, b1, c1, d1, e1 = [1, a, a**2, a**3], [1, b, b**2, b**3], [1, c, c**2, c**3], [1, d, d**2, d**3], [1, e, e**2, e**3]

a2, b2, c2, d2, e2 = 24, 20, 10, 13, 12

x = np.array([a1, b1, c1, d1, e1])

y = np.array([[a2], [b2], [c2], [d2], [e2]])

xx = np.matmul(x.transpose(), x)
xxmi = xx + 2*np.identity(4)
xi = np.linalg.inv(xxmi)
xix = np.matmul(xi, x.transpose())
w = np.matmul(xix, y)

print(w)

[[ 7.0450759 ]
 [ 4.64092765]
 [ 1.96734046]
 [-1.30088142]]


In [4]:
sum = 0
for i in range(5):
    sum += (y[i][0] - np.matmul(x[i], w))**2

RMSE = (sum/5)**0.5

print(RMSE)

[6.84329489]


In [6]:
w1 = np.array([[1], [1]])
x0 = np.array([[0.8, 1, 1.2]])
b1 = np.array([[1], [1]])

z1 = np.matmul(w1, x0) + b1
x1 = np.exp(0.1 * z1)

#-------------------
w2 = np.array([[1, 1]])
b2 = np.array([[1]])

z2 = np.matmul(w2, x1) + b2
x2 = np.exp(0.1 * z2)

for j in range(1):

    #------------------------------------------------
    # w2 atualização
    #------------------------------------------------
    t = [24, 20, 10]
    delta2 = np.array([(x2[0][0]-t[0]) * (0.1 * x2[0][0])])
    for i in range(1, 3):
        n = ((x2[0][i]-t[i]) * (0.1 * x2[0][i]))
        delta2 = np.column_stack((delta2, n))

    dEdw2 = np.matmul(delta2, np.transpose(x1))
    w2_atualizado = w2 - 0.1 * dEdw2

    print("-------\nw2: \n", w2_atualizado)

    #------------------------------------------------
    # b2 atualização
    #------------------------------------------------
    dEdb2 = np.matmul(delta2, [[1], [1], [1]])
    b2_atualizado = b2 - 0.1 * dEdb2

    print("-------\nb2: \n", b2_atualizado)

    #------------------------------------------------
    # w1 atualização
    #------------------------------------------------

    delta1 = np.array(np.transpose(w2) * delta2[0][0] * (0.1 * x1[0][0]))
    for i in range(1, 3):
        n = (np.transpose(w2) * delta2[0][i] * (0.1 * x1[0][i]))
        delta1 = np.column_stack((delta1, n))

    dEdw1 = np.matmul(delta1, np.transpose(x0))

    w1_atualizado = w1 - 0.1 * dEdw1

    print("-------\nw1: \n", w1_atualizado)

    #------------------------------------------------
    # b1 atualização
    #------------------------------------------------
    dEdb1 = np.matmul(delta1, [[1], [1], [1]])
    b1_atualizado = b1 - 0.1 * dEdb1

    print("-------\nb1: \n", b1_atualizado)

    #------------------------------------------------
    #------------------------------------------------

    z1_atualizado = np.matmul(w1_atualizado, x0) + b1_atualizado
    x1_atualizado = np.exp(0.1 * z1_atualizado)
    #-------------------
    z2_atualizado = np.matmul(w2_atualizado, x1_atualizado) + b2_atualizado
    x2_atualizado = np.exp(0.1 * z2_atualizado)

    w1 = w1_atualizado
    w2 = w2_atualizado
    b1 = b1_atualizado
    b2 = b2_atualizado
    x1 = x1_atualizado
    x2 = x2_atualizado

#print(x2_atualizado)

[[3.39443473 3.44280552 3.49215346]]
-------
w2: 
 [[1.8518485 1.8518485]]
-------
b2: 
 [[1.7012589]]
-------
w1: 
 [[1.08062041]
 [1.08062041]]
-------
b1: 
 [[1.08518485]
 [1.08518485]]
