In [7]:
import numpy as np

x1 = np.array([[1], [2]])
x2 = np.array([[-1], [1]])
x3 = np.array([[1], [0]])

u1 = np.array([[2], [2]])
u2 = np.array([[0], [0]])

sigma1 = np.array([[2, 1], [1, 2]])
sigma2 = np.array([[2, 0], [0, 2]])

pi1 = 0.5
pi2 = 0.5

def gaussian(x, u, sigma):
    return 1 / (2 * np.pi * np.sqrt(np.linalg.det(sigma))) * np.exp(-0.5 * (x - u).T @ np.linalg.inv(sigma) @ (x - u))

In [8]:
# exercise 1

#--------------------------------------------
# E-step
#--------------------------------------------
# x1:

p1 = pi1 * gaussian(x1, u1, sigma1)
p2 = pi2 * gaussian(x1, u2, sigma2)

p1_x1 = p1 / (p1 + p2)
p2_x1 = p2 / (p1 + p2)
# x2:

p1 = pi1 * gaussian(x2, u1, sigma1)
p2 = pi2 * gaussian(x2, u2, sigma2)

p1_x2 = p1 / (p1 + p2)
p2_x2 = p2 / (p1 + p2)

# x3:

p1 = pi1 * gaussian(x3, u1, sigma1)
p2 = pi2 * gaussian(x3, u2, sigma2)

p1_x3 = p1 / (p1 + p2)
p2_x3 = p2 / (p1 + p2)

In [9]:
# exercise 1 continued

#--------------------------------------------
# M-step
#--------------------------------------------

def recalculate_u(x1, x2, x3, p1, p2, p3):
    return (p1 * x1 + p2 * x2 + p3 * x3)/(p1 + p2 + p3)

def recalculate_sigma(x1, x2, x3, u, p1, p2, p3):
    return (np.multiply((x1 - u), np.transpose(x1 - u)) * p1 + \
        np.multiply((x2 - u), np.transpose(x2 - u)) * p2 + \
        np.multiply((x3 - u), np.transpose(x3 - u)) * p3) / (p1 + p2 + p3)

def recalculate_pi(p1, p2, p3):
    return (p1 + p2 + p3) / 3

# cluster 1:

u1_new = recalculate_u(x1, x2, x3, p1_x1, p1_x2, p1_x3)

sigma1_new = recalculate_sigma(x1, x2, x3, u1_new, p1_x1, p1_x2, p1_x3)

pi1_new = recalculate_pi(p1_x1, p1_x2, p1_x3)

print(u1_new)
print(sigma1_new)
print(pi1_new)


# cluster 2:

u2_new = recalculate_u(x1, x2, x3, p2_x1, p2_x2, p2_x3)

sigma2_new = recalculate_sigma(x1, x2, x3, u2_new, p2_x1, p2_x2, p2_x3)

pi2_new = recalculate_pi(p2_x1, p2_x2, p2_x3)

print(u2_new)
print(sigma2_new)
print(pi2_new)


[[0.75096381]
 [1.31149108]]
[[0.43605335 0.07757255]
 [0.07757255 0.77845521]]
[[0.41718869]]
[[0.03438459]
 [0.77702808]]
[[ 0.9988177  -0.21530512]
 [-0.21530512  0.46747582]]
[[0.58281131]]


In [10]:
# exercise 2
# a)

# x1:

p1 = pi1_new * gaussian(x1, u1_new, sigma1_new) # 0.08164192
p2 = pi2_new * gaussian(x1, u2_new, sigma2_new) # 0.00787938

p1_norm = p1 / (p1 + p2) # 0.91198316 !!!! c1
p2_norm = p2 / (p1 + p2) # 0.08801684

print("weight of cluster 1 for x1: ", p1_norm)
print("weight of cluster 2 for x1: ", p2_norm)

# x2:

p1 = pi1_new * gaussian(x2, u1_new, sigma1_new) # 0.00341898
p2 = pi2_new * gaussian(x2, u2_new, sigma2_new) # 0.08371795

p1_norm = p1 / (p1 + p2) # 0.03923683
p2_norm = p2 / (p1 + p2) # 0.96076317 !!!! c2

print("weight of cluster 1 for x2: ", p1_norm)
print("weight of cluster 2 for x2: ", p2_norm)

# x3:

p1 = pi1_new * gaussian(x3, u1_new, sigma1_new) # 0.03219282
p2 = pi2_new * gaussian(x3, u2_new, sigma2_new) # 0.06106939

p1_norm = p1 / (p1 + p2) # 0.3451861
p2_norm = p2 / (p1 + p2) # 0.6548139 !!!! c2

print("weight of cluster 1 for x3: ", p1_norm)
print("weight of cluster 2 for x3: ", p2_norm)

weight of cluster 1 for x1:  [[0.91198316]]
weight of cluster 2 for x1:  [[0.08801684]]
weight of cluster 1 for x2:  [[0.03923683]]
weight of cluster 2 for x2:  [[0.96076317]]
weight of cluster 1 for x3:  [[0.3451861]]
weight of cluster 2 for x3:  [[0.6548139]]


In [11]:
# exercise 2

# b)

def euclidean_distance(x1, x2):
    return np.sqrt(np.sum(np.square(x1 - x2)))

silhouette_x2 = 1 - euclidean_distance(x2, x3) / euclidean_distance(x2, x1) # bc a < b -> 1 - a/b
silhouette_x3 = euclidean_distance(x3, x1)/euclidean_distance(x3, x2) - 1 # bc a > b -> b/a - 1

silhouette_c2 = (silhouette_x2 + silhouette_x3) / 2

print("x2:", silhouette_x2)
print("x3:", silhouette_x3)
print("c2:", silhouette_c2)


x2: 0.0
x3: -0.10557280900008414
c2: -0.05278640450004207
